version: '3.3'
services:
    docker-ripper:
        container_name: Ripper
        volumes:
            - '/tmp/ripper/:/config:rw'
            - '/tmp/ripper/:/out:rw'
        devices:
            - '/dev/sr0:/dev/sr0'
            - '/dev/sg0:/dev/sg0'
        image: rix1337/docker-ripper
